export default function handler(req, res) {
  res.send(`{
    "subject":"acct:mfenner@hachyderm.io",
    "aliases":
    [
        "https://hachyderm.io/@mfenner",
        "https://hachyderm.io/users/mfenner"
    ],
    "links":
    [
        {
            "rel":"http://webfinger.net/rel/profile-page",
            "type":"text/html",
            "href":"https://hachyderm.io/@mfenner"
        },
        {
            "rel":"self",
            "type":"application/activity+json",
            "href":"https://hachyderm.io/users/mfenner"
        },
        {
            "rel":"http://ostatus.org/schema/1.0/subscribe",
            "template":"https://hachyderm.io/authorize_interaction?uri={uri}"
        }
    ]
}`)
}
